### ISSUE TITLE
Inclusion in i3scripts collection

### ISSUE THREAD

**Issue by slackhead** [olemartinorg/i3-alternating-layout#10]
Hi

I'm part of a project to collect useful i3 scripts and would like to add yours. I did see the license but I thought it proper to say hi and ask :)

Our repo is here:

https://github.com/i3script/awesome-i3wm

**Comment by olemartinorg** [comment]
Sure thing! It would be an honour to be added to your list! :-)
The license file is right there in the project root, though.

**Comment by slackhead** [comment]
Thanks.
