### ISSUE TITLE
Arch Linux new dependency

### ISSUE THREAD

**Issue by damarusama** [olemartinorg/i3-alternating-layout#12]
The package that needs to be installed are: 

python-i3-py
xorg-util-macros

Then you can install this no problem. I'll comment on the AUR package too

**Comment by olemartinorg** [comment]
Hi! Sorry for being extremely late with this. I'm not using the script myself, so I don't really keep up with the needed changes. Can you look over the readme now and see if my latest change fixes things?

**Comment by damarusama** [comment]
Thanks that seems to work fine now.

**Comment by riaschroeder** [comment]
Both python-i3-py xorg-util-macros not needed now
Can you remove it from dependency in aur package?

**Comment by olemartinorg** [comment]
@riaschroeder You might have better luck writing a comment on AUR, maybe? I don't know here @damarusama is easiest to reach.
