### ISSUE TITLE
Random error when running in the background

### ISSUE THREAD

**Issue by marioortizmanero** [olemartinorg/i3-alternating-layout#15]
Sometimes when I'm running this script it closes itself with this error:

```python
    Traceback (most recent call last):
      File ".config/i3/scripts/alternating_layouts.py", line 109, in <module>
        main()
      File ".config/i3/scripts/alternating_layouts.py", line 102, in main
        set_layout()
      File ".config/i3/scripts/alternating_layouts.py", line 41, in set_layout
        current_win = i3.filter(nodes=[], focused=True)
      File "/usr/lib/python3.7/site-packages/i3.py", line 508, in filter
        tree = msg('get_tree')
      File "/usr/lib/python3.7/site-packages/i3.py", line 392, in msg
        response = default_socket().get(type, message)
      File "/usr/lib/python3.7/site-packages/i3.py", line 181, in get
        self.send(msg_type, payload)
      File "/usr/lib/python3.7/site-packages/i3.py", line 203, in send
        self.socket.sendall(message)
    BrokenPipeError: [Errno 32] Broken pipe
```

I'm running arch and followed the install guide

**Comment by olemartinorg** [comment]
This shouldn't happen randomly. Does it happen when you restart i3wm?
See #14, it was reported there as well, but only when restarting i3wm. Does it work better if you start it with `exec_always` instead?

**Comment by marioortizmanero** [comment]
I'll try using exec_always and I'll report back. I've added a very ugly looking try and catch that just restarts the script anyway. Also, i3-py is deprecated, could it be something related to that, too?

**Comment by iFreilicht** [comment]
This seems to be an issue with i3-py. As I wrote in #16, there is a replacement called [i3ipc-python](https://github.com/altdesktop/i3ipc-python). Rewriting this tool slightly to use the new module would likely solve this issue.

**Comment by neilbags** [comment]
I'm also using a try/except in a loop to workaround this error. See https://github.com/olemartinorg/i3-alternating-layout/pull/22

**Comment by olemartinorg** [comment]
i3-py has now been replaced with i3ipc, by merging #26. Closing this, but do not hesitate to reach out if this causes any new problems.
