### ISSUE TITLE
Is this repository obsolete?

### ISSUE THREAD

**Issue by iFreilicht** [olemartinorg/i3-alternating-layout#19]
You can get an alternating layout in just two lines (see [this comment](https://github.com/i3/i3/issues/2106#issuecomment-343843244)):

```
default_orientation vertical
for_window [class="^"] split toggle
```
Is there something your code achieves that this doesn't?

**Comment by olemartinorg** [comment]
Nice hack!
I haven't tried it, but it seems it just toggles the split orientation every time a new window opens? That means, it will toggle the split orientation even if your browser opens a popup, right?

This script does not simply toggle the split orientation every time, it looks at the currently focused window and uses the window dimensions (width/height) to decide on the next split orientation should you choose to open a new window.

**Comment by iFreilicht** [comment]
You're right, and now that I've used this setup for a day, it actually got in my way one or two times. I'll have a go at your solution.

Thanks a lot for the explanation!
