### ISSUE TITLE
moving containers inhibited

### ISSUE THREAD

**Issue by oberon2007** [olemartinorg/i3-alternating-layout#7]
Unfortunately i3's functionality of moving containers with ``move left/right/up/down`` (default keybinding mod+Shift+j/k/l/ö/;/arrow-keys) is messed up by the script ...
ideas? @Airblader ?

**Comment by olemartinorg** [comment]
I added a command-line option (```-p path/to/pid.file```) that allows you to save the PID of the script to a file, so that you can pause and resume the script using ```pkill -STOP -F path/to/pid.file``` and ```pkill -CONT -F path/to/pid.file```. If you surround your calls to the move commands in i3 with a stop and a cont, they will work as expected.

**Comment by oberon2007** [comment]
Thank you. What makes me a bit unhappy with this solution is the necessary config at user level, meaning that installation by means of a package becomes a bit unsatisfactory ... But it looks like a clever workaround. Will test it :)

**Comment by Airblader** [comment]
Imho that's getting really hacky. At this point I'd really just wait for split toggle to be in a release.

**Comment by oberon2007** [comment]
Would there be a way that the script listens to the 'move' commands and reacts to them? In fact **alternating_layouts.py** would have to be a wrapper to what it is doing right now, if you see what I mean.

**Comment by olemartinorg** [comment]
This whole script is a hack, but as far as i've found it's the only way of doing things in lieu of an official mode from i3wm. I could also have made a patch to i3 itself, but i don't really know that much C - and i don't really use this script myself, i just made it for someone on reddit a while back.

As far as i know, there's no way to hook into i3 and listen for their move commands, no. It's not available in the IPC interface, at least.

**Comment by Airblader** [comment]
We recently merged a new command "split toggle"  which you can use to do something extremely similar to this script. It's just not in a released version yet. 

For Manjaro-i3 I'd suggest waiting this out or updating the package.

**Comment by oberon2007** [comment]
Well the funny thing is that this problem is now present also without the alternating-layouts script and the new ``split toggle`` function of i3 activated ;)
