### ISSUE TITLE
screenshot showing wrong layout

### ISSUE THREAD

**Issue by stloewen** [olemartinorg/i3-alternating-layout#9]
Just a little comment:
Since c74dfc889700a63c03b9c5325bd416d3d8e07944 the screenshot is wrong.

Since the split-orientation is calculated based on width/height pressing only `$mod+Return` creates a different layout than the depicted one.

**Comment by olemartinorg** [comment]
Thanks for the comment! And sorry for my late reply...
I pushed an updated screenshot now, but I see that the github caching still haven't updated. I'll check back and possibly change the filename if they don't invalidate their cached version.

**Comment by olemartinorg** [comment]
Allright, the new screenshot is shown now - It only took them a few minutes.. :-)
